// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: guests.sql

package guestdb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countGuests = `-- name: CountGuests :one
SELECT count(*) FROM guests
WHERE wedding_id = $1
  AND ($2::text IS NULL OR rsvp_status = $2)
  AND ($3::text IS NULL OR group_name = $3)
  AND ($4::boolean IS NULL OR (shared_at IS NOT NULL) = $4)
  AND ($5::text IS NULL
       OR name ILIKE '%' || $5 || '%'
       OR phone LIKE '%' || $5 || '%'
       OR email::text ILIKE '%' || $5 || '%'
       OR invitation_code = upper($5))
`

type CountGuestsParams struct {
	WeddingID uuid.UUID
	Status    *string
	GroupName *string
	Shared    *bool
	Q         *string
}

func (q *Queries) CountGuests(ctx context.Context, arg CountGuestsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countGuests,
		arg.WeddingID,
		arg.Status,
		arg.GroupName,
		arg.Shared,
		arg.Q,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRSVPResponses = `-- name: CountRSVPResponses :one
SELECT count(*) FROM guests
WHERE wedding_id = $1
  AND rsvp_at IS NOT NULL
  AND ($2::text IS NULL OR rsvp_status = $2)
`

type CountRSVPResponsesParams struct {
	WeddingID uuid.UUID
	Status    *string
}

func (q *Queries) CountRSVPResponses(ctx context.Context, arg CountRSVPResponsesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRSVPResponses, arg.WeddingID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createGuest = `-- name: CreateGuest :one
INSERT INTO guests (id, wedding_id, name, phone, email, group_name, max_pax, invitation_code, notes)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, wedding_id, name, phone, email, group_name, max_pax, invitation_code, rsvp_status, rsvp_pax, rsvp_message, rsvp_at, attendance_status, notes, last_opened_at, created_at, updated_at, shared_at, checked_in_at, checked_in_pax, checked_in_via
`

type CreateGuestParams struct {
	ID             uuid.UUID
	WeddingID      uuid.UUID
	Name           string
	Phone          string
	Email          *string
	GroupName      string
	MaxPax         int16
	InvitationCode string
	Notes          string
}

func (q *Queries) CreateGuest(ctx context.Context, arg CreateGuestParams) (Guest, error) {
	row := q.db.QueryRow(ctx, createGuest,
		arg.ID,
		arg.WeddingID,
		arg.Name,
		arg.Phone,
		arg.Email,
		arg.GroupName,
		arg.MaxPax,
		arg.InvitationCode,
		arg.Notes,
	)
	var i Guest
	err := row.Scan(
		&i.ID,
		&i.WeddingID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.GroupName,
		&i.MaxPax,
		&i.InvitationCode,
		&i.RsvpStatus,
		&i.RsvpPax,
		&i.RsvpMessage,
		&i.RsvpAt,
		&i.AttendanceStatus,
		&i.Notes,
		&i.LastOpenedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SharedAt,
		&i.CheckedInAt,
		&i.CheckedInPax,
		&i.CheckedInVia,
	)
	return i, err
}

const deleteGuest = `-- name: DeleteGuest :execrows
DELETE FROM guests WHERE id = $1 AND wedding_id = $2
`

type DeleteGuestParams struct {
	ID        uuid.UUID
	WeddingID uuid.UUID
}

func (q *Queries) DeleteGuest(ctx context.Context, arg DeleteGuestParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteGuest, arg.ID, arg.WeddingID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteGuests = `-- name: DeleteGuests :execrows
DELETE FROM guests WHERE wedding_id = $1 AND id = ANY($2::uuid[])
`

type DeleteGuestsParams struct {
	WeddingID uuid.UUID
	Ids       []uuid.UUID
}

func (q *Queries) DeleteGuests(ctx context.Context, arg DeleteGuestsParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteGuests, arg.WeddingID, arg.Ids)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteShareTemplate = `-- name: DeleteShareTemplate :exec
DELETE FROM share_templates WHERE wedding_id = $1
`

func (q *Queries) DeleteShareTemplate(ctx context.Context, weddingID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteShareTemplate, weddingID)
	return err
}

const getGuest = `-- name: GetGuest :one
SELECT id, wedding_id, name, phone, email, group_name, max_pax, invitation_code, rsvp_status, rsvp_pax, rsvp_message, rsvp_at, attendance_status, notes, last_opened_at, created_at, updated_at, shared_at, checked_in_at, checked_in_pax, checked_in_via FROM guests WHERE id = $1 AND wedding_id = $2
`

type GetGuestParams struct {
	ID        uuid.UUID
	WeddingID uuid.UUID
}

func (q *Queries) GetGuest(ctx context.Context, arg GetGuestParams) (Guest, error) {
	row := q.db.QueryRow(ctx, getGuest, arg.ID, arg.WeddingID)
	var i Guest
	err := row.Scan(
		&i.ID,
		&i.WeddingID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.GroupName,
		&i.MaxPax,
		&i.InvitationCode,
		&i.RsvpStatus,
		&i.RsvpPax,
		&i.RsvpMessage,
		&i.RsvpAt,
		&i.AttendanceStatus,
		&i.Notes,
		&i.LastOpenedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SharedAt,
		&i.CheckedInAt,
		&i.CheckedInPax,
		&i.CheckedInVia,
	)
	return i, err
}

const getGuestByCode = `-- name: GetGuestByCode :one
SELECT id, wedding_id, name, phone, email, group_name, max_pax, invitation_code, rsvp_status, rsvp_pax, rsvp_message, rsvp_at, attendance_status, notes, last_opened_at, created_at, updated_at, shared_at, checked_in_at, checked_in_pax, checked_in_via FROM guests WHERE invitation_code = $1
`

// tenant:ignore kode undangan unik global; wedding di-resolve dari hasilnya (resolver T09)
func (q *Queries) GetGuestByCode(ctx context.Context, invitationCode string) (Guest, error) {
	row := q.db.QueryRow(ctx, getGuestByCode, invitationCode)
	var i Guest
	err := row.Scan(
		&i.ID,
		&i.WeddingID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.GroupName,
		&i.MaxPax,
		&i.InvitationCode,
		&i.RsvpStatus,
		&i.RsvpPax,
		&i.RsvpMessage,
		&i.RsvpAt,
		&i.AttendanceStatus,
		&i.Notes,
		&i.LastOpenedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SharedAt,
		&i.CheckedInAt,
		&i.CheckedInPax,
		&i.CheckedInVia,
	)
	return i, err
}

const getShareTemplate = `-- name: GetShareTemplate :one
SELECT wedding_id, language, body, updated_at FROM share_templates WHERE wedding_id = $1
`

func (q *Queries) GetShareTemplate(ctx context.Context, weddingID uuid.UUID) (ShareTemplate, error) {
	row := q.db.QueryRow(ctx, getShareTemplate, weddingID)
	var i ShareTemplate
	err := row.Scan(
		&i.WeddingID,
		&i.Language,
		&i.Body,
		&i.UpdatedAt,
	)
	return i, err
}

const guestStats = `-- name: GuestStats :one
SELECT
    count(*)                                                  AS total,
    count(*) FILTER (WHERE rsvp_status = 'attending')         AS attending,
    count(*) FILTER (WHERE rsvp_status = 'declined')          AS declined,
    count(*) FILTER (WHERE rsvp_status = 'pending')           AS pending,
    COALESCE(sum(max_pax), 0)::bigint                         AS pax_invited,
    COALESCE(sum(rsvp_pax) FILTER (WHERE rsvp_status = 'attending'), 0)::bigint AS pax_attending,
    count(*) FILTER (WHERE last_opened_at IS NOT NULL)        AS opened
FROM guests WHERE wedding_id = $1
`

type GuestStatsRow struct {
	Total        int64
	Attending    int64
	Declined     int64
	Pending      int64
	PaxInvited   int64
	PaxAttending int64
	Opened       int64
}

func (q *Queries) GuestStats(ctx context.Context, weddingID uuid.UUID) (GuestStatsRow, error) {
	row := q.db.QueryRow(ctx, guestStats, weddingID)
	var i GuestStatsRow
	err := row.Scan(
		&i.Total,
		&i.Attending,
		&i.Declined,
		&i.Pending,
		&i.PaxInvited,
		&i.PaxAttending,
		&i.Opened,
	)
	return i, err
}

type InsertGuestsParams struct {
	ID             uuid.UUID
	WeddingID      uuid.UUID
	Name           string
	Phone          string
	Email          *string
	GroupName      string
	MaxPax         int16
	InvitationCode string
}

const listAllGuests = `-- name: ListAllGuests :many
SELECT id, wedding_id, name, phone, email, group_name, max_pax, invitation_code, rsvp_status, rsvp_pax, rsvp_message, rsvp_at, attendance_status, notes, last_opened_at, created_at, updated_at, shared_at, checked_in_at, checked_in_pax, checked_in_via FROM guests WHERE wedding_id = $1 ORDER BY lower(name), id
`

func (q *Queries) ListAllGuests(ctx context.Context, weddingID uuid.UUID) ([]Guest, error) {
	rows, err := q.db.Query(ctx, listAllGuests, weddingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Guest{}
	for rows.Next() {
		var i Guest
		if err := rows.Scan(
			&i.ID,
			&i.WeddingID,
			&i.Name,
			&i.Phone,
			&i.Email,
			&i.GroupName,
			&i.MaxPax,
			&i.InvitationCode,
			&i.RsvpStatus,
			&i.RsvpPax,
			&i.RsvpMessage,
			&i.RsvpAt,
			&i.AttendanceStatus,
			&i.Notes,
			&i.LastOpenedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SharedAt,
			&i.CheckedInAt,
			&i.CheckedInPax,
			&i.CheckedInVia,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroups = `-- name: ListGroups :many
SELECT DISTINCT group_name FROM guests
WHERE wedding_id = $1 AND group_name <> ''
ORDER BY group_name
`

func (q *Queries) ListGroups(ctx context.Context, weddingID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listGroups, weddingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var group_name string
		if err := rows.Scan(&group_name); err != nil {
			return nil, err
		}
		items = append(items, group_name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGuests = `-- name: ListGuests :many
SELECT id, wedding_id, name, phone, email, group_name, max_pax, invitation_code, rsvp_status, rsvp_pax, rsvp_message, rsvp_at, attendance_status, notes, last_opened_at, created_at, updated_at, shared_at, checked_in_at, checked_in_pax, checked_in_via FROM guests
WHERE wedding_id = $1
  AND ($2::text IS NULL OR rsvp_status = $2)
  AND ($3::text IS NULL OR group_name = $3)
  AND ($4::boolean IS NULL OR (shared_at IS NOT NULL) = $4)
  AND ($5::text IS NULL
       OR name ILIKE '%' || $5 || '%'
       OR phone LIKE '%' || $5 || '%'
       OR email::text ILIKE '%' || $5 || '%'
       OR invitation_code = upper($5))
ORDER BY lower(name), id
LIMIT $7 OFFSET $6
`

type ListGuestsParams struct {
	WeddingID uuid.UUID
	Status    *string
	GroupName *string
	Shared    *bool
	Q         *string
	Off       int32
	Lim       int32
}

func (q *Queries) ListGuests(ctx context.Context, arg ListGuestsParams) ([]Guest, error) {
	rows, err := q.db.Query(ctx, listGuests,
		arg.WeddingID,
		arg.Status,
		arg.GroupName,
		arg.Shared,
		arg.Q,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Guest{}
	for rows.Next() {
		var i Guest
		if err := rows.Scan(
			&i.ID,
			&i.WeddingID,
			&i.Name,
			&i.Phone,
			&i.Email,
			&i.GroupName,
			&i.MaxPax,
			&i.InvitationCode,
			&i.RsvpStatus,
			&i.RsvpPax,
			&i.RsvpMessage,
			&i.RsvpAt,
			&i.AttendanceStatus,
			&i.Notes,
			&i.LastOpenedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SharedAt,
			&i.CheckedInAt,
			&i.CheckedInPax,
			&i.CheckedInVia,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRSVPResponses = `-- name: ListRSVPResponses :many
SELECT id, wedding_id, name, phone, email, group_name, max_pax, invitation_code, rsvp_status, rsvp_pax, rsvp_message, rsvp_at, attendance_status, notes, last_opened_at, created_at, updated_at, shared_at, checked_in_at, checked_in_pax, checked_in_via FROM guests
WHERE wedding_id = $1
  AND rsvp_at IS NOT NULL
  AND ($2::text IS NULL OR rsvp_status = $2)
ORDER BY rsvp_at DESC, id
LIMIT $4 OFFSET $3
`

type ListRSVPResponsesParams struct {
	WeddingID uuid.UUID
	Status    *string
	Off       int32
	Lim       int32
}

func (q *Queries) ListRSVPResponses(ctx context.Context, arg ListRSVPResponsesParams) ([]Guest, error) {
	rows, err := q.db.Query(ctx, listRSVPResponses,
		arg.WeddingID,
		arg.Status,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Guest{}
	for rows.Next() {
		var i Guest
		if err := rows.Scan(
			&i.ID,
			&i.WeddingID,
			&i.Name,
			&i.Phone,
			&i.Email,
			&i.GroupName,
			&i.MaxPax,
			&i.InvitationCode,
			&i.RsvpStatus,
			&i.RsvpPax,
			&i.RsvpMessage,
			&i.RsvpAt,
			&i.AttendanceStatus,
			&i.Notes,
			&i.LastOpenedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SharedAt,
			&i.CheckedInAt,
			&i.CheckedInPax,
			&i.CheckedInVia,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOpened = `-- name: MarkOpened :exec
UPDATE guests SET last_opened_at = $3 WHERE id = $1 AND wedding_id = $2
`

type MarkOpenedParams struct {
	ID           uuid.UUID
	WeddingID    uuid.UUID
	LastOpenedAt *time.Time
}

func (q *Queries) MarkOpened(ctx context.Context, arg MarkOpenedParams) error {
	_, err := q.db.Exec(ctx, markOpened, arg.ID, arg.WeddingID, arg.LastOpenedAt)
	return err
}

const markShared = `-- name: MarkShared :execrows
UPDATE guests SET shared_at = $3 WHERE id = $1 AND wedding_id = $2
`

type MarkSharedParams struct {
	ID        uuid.UUID
	WeddingID uuid.UUID
	SharedAt  *time.Time
}

func (q *Queries) MarkShared(ctx context.Context, arg MarkSharedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markShared, arg.ID, arg.WeddingID, arg.SharedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateGuest = `-- name: UpdateGuest :one
UPDATE guests
SET name = $3, phone = $4, email = $5, group_name = $6, max_pax = $7, notes = $8
WHERE id = $1 AND wedding_id = $2
RETURNING id, wedding_id, name, phone, email, group_name, max_pax, invitation_code, rsvp_status, rsvp_pax, rsvp_message, rsvp_at, attendance_status, notes, last_opened_at, created_at, updated_at, shared_at, checked_in_at, checked_in_pax, checked_in_via
`

type UpdateGuestParams struct {
	ID        uuid.UUID
	WeddingID uuid.UUID
	Name      string
	Phone     string
	Email     *string
	GroupName string
	MaxPax    int16
	Notes     string
}

func (q *Queries) UpdateGuest(ctx context.Context, arg UpdateGuestParams) (Guest, error) {
	row := q.db.QueryRow(ctx, updateGuest,
		arg.ID,
		arg.WeddingID,
		arg.Name,
		arg.Phone,
		arg.Email,
		arg.GroupName,
		arg.MaxPax,
		arg.Notes,
	)
	var i Guest
	err := row.Scan(
		&i.ID,
		&i.WeddingID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.GroupName,
		&i.MaxPax,
		&i.InvitationCode,
		&i.RsvpStatus,
		&i.RsvpPax,
		&i.RsvpMessage,
		&i.RsvpAt,
		&i.AttendanceStatus,
		&i.Notes,
		&i.LastOpenedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SharedAt,
		&i.CheckedInAt,
		&i.CheckedInPax,
		&i.CheckedInVia,
	)
	return i, err
}

const updateRSVP = `-- name: UpdateRSVP :one
UPDATE guests
SET rsvp_status = $3, rsvp_pax = $4, rsvp_message = $5, rsvp_at = $6
WHERE id = $1 AND wedding_id = $2
RETURNING id, wedding_id, name, phone, email, group_name, max_pax, invitation_code, rsvp_status, rsvp_pax, rsvp_message, rsvp_at, attendance_status, notes, last_opened_at, created_at, updated_at, shared_at, checked_in_at, checked_in_pax, checked_in_via
`

type UpdateRSVPParams struct {
	ID          uuid.UUID
	WeddingID   uuid.UUID
	RsvpStatus  string
	RsvpPax     int16
	RsvpMessage string
	RsvpAt      *time.Time
}

func (q *Queries) UpdateRSVP(ctx context.Context, arg UpdateRSVPParams) (Guest, error) {
	row := q.db.QueryRow(ctx, updateRSVP,
		arg.ID,
		arg.WeddingID,
		arg.RsvpStatus,
		arg.RsvpPax,
		arg.RsvpMessage,
		arg.RsvpAt,
	)
	var i Guest
	err := row.Scan(
		&i.ID,
		&i.WeddingID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.GroupName,
		&i.MaxPax,
		&i.InvitationCode,
		&i.RsvpStatus,
		&i.RsvpPax,
		&i.RsvpMessage,
		&i.RsvpAt,
		&i.AttendanceStatus,
		&i.Notes,
		&i.LastOpenedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SharedAt,
		&i.CheckedInAt,
		&i.CheckedInPax,
		&i.CheckedInVia,
	)
	return i, err
}

const upsertShareTemplate = `-- name: UpsertShareTemplate :exec
INSERT INTO share_templates (wedding_id, language, body) VALUES ($1, $2, $3)
ON CONFLICT (wedding_id) DO UPDATE SET language = EXCLUDED.language, body = EXCLUDED.body
`

type UpsertShareTemplateParams struct {
	WeddingID uuid.UUID
	Language  string
	Body      string
}

func (q *Queries) UpsertShareTemplate(ctx context.Context, arg UpsertShareTemplateParams) error {
	_, err := q.db.Exec(ctx, upsertShareTemplate, arg.WeddingID, arg.Language, arg.Body)
	return err
}
