// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin.sql

package admindb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const assignPackage = `-- name: AssignPackage :exec
INSERT INTO wedding_packages (wedding_id, package_id, assigned_at) VALUES ($1, $2, $3)
ON CONFLICT (wedding_id) DO UPDATE SET package_id = EXCLUDED.package_id, assigned_at = EXCLUDED.assigned_at
`

type AssignPackageParams struct {
	WeddingID  uuid.UUID
	PackageID  uuid.UUID
	AssignedAt time.Time
}

func (q *Queries) AssignPackage(ctx context.Context, arg AssignPackageParams) error {
	_, err := q.db.Exec(ctx, assignPackage, arg.WeddingID, arg.PackageID, arg.AssignedAt)
	return err
}

const countAuditLogs = `-- name: CountAuditLogs :one
SELECT count(*) FROM admin_audit_logs
WHERE ($1::text IS NULL OR target_id = $1)
`

func (q *Queries) CountAuditLogs(ctx context.Context, targetID *string) (int64, error) {
	row := q.db.QueryRow(ctx, countAuditLogs, targetID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPackage = `-- name: CreatePackage :one
INSERT INTO packages (id, name, storage_mb, archive_days, price_display, show_on_landing, sort_order)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, name, storage_mb, archive_days, price_display, created_at, updated_at, show_on_landing, sort_order
`

type CreatePackageParams struct {
	ID            uuid.UUID
	Name          string
	StorageMb     int32
	ArchiveDays   int32
	PriceDisplay  string
	ShowOnLanding bool
	SortOrder     int32
}

func (q *Queries) CreatePackage(ctx context.Context, arg CreatePackageParams) (Package, error) {
	row := q.db.QueryRow(ctx, createPackage,
		arg.ID,
		arg.Name,
		arg.StorageMb,
		arg.ArchiveDays,
		arg.PriceDisplay,
		arg.ShowOnLanding,
		arg.SortOrder,
	)
	var i Package
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.StorageMb,
		&i.ArchiveDays,
		&i.PriceDisplay,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ShowOnLanding,
		&i.SortOrder,
	)
	return i, err
}

const deletePackage = `-- name: DeletePackage :execrows
DELETE FROM packages WHERE id = $1
`

func (q *Queries) DeletePackage(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deletePackage, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getPackage = `-- name: GetPackage :one
SELECT id, name, storage_mb, archive_days, price_display, created_at, updated_at, show_on_landing, sort_order FROM packages WHERE id = $1
`

func (q *Queries) GetPackage(ctx context.Context, id uuid.UUID) (Package, error) {
	row := q.db.QueryRow(ctx, getPackage, id)
	var i Package
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.StorageMb,
		&i.ArchiveDays,
		&i.PriceDisplay,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ShowOnLanding,
		&i.SortOrder,
	)
	return i, err
}

const getWeddingPackage = `-- name: GetWeddingPackage :one
SELECT p.id, p.name, p.storage_mb, p.archive_days, p.price_display, p.created_at, p.updated_at, p.show_on_landing, p.sort_order FROM wedding_packages wp JOIN packages p ON p.id = wp.package_id
WHERE wp.wedding_id = $1
`

func (q *Queries) GetWeddingPackage(ctx context.Context, weddingID uuid.UUID) (Package, error) {
	row := q.db.QueryRow(ctx, getWeddingPackage, weddingID)
	var i Package
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.StorageMb,
		&i.ArchiveDays,
		&i.PriceDisplay,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ShowOnLanding,
		&i.SortOrder,
	)
	return i, err
}

const insertAuditLog = `-- name: InsertAuditLog :exec
INSERT INTO admin_audit_logs (id, admin_user_id, admin_email, action, target_type, target_id, details, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertAuditLogParams struct {
	ID          uuid.UUID
	AdminUserID *uuid.UUID
	AdminEmail  string
	Action      string
	TargetType  string
	TargetID    string
	Details     []byte
	CreatedAt   time.Time
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.Exec(ctx, insertAuditLog,
		arg.ID,
		arg.AdminUserID,
		arg.AdminEmail,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.Details,
		arg.CreatedAt,
	)
	return err
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT id, admin_user_id, admin_email, action, target_type, target_id, details, created_at FROM admin_audit_logs
WHERE ($1::text IS NULL OR target_id = $1)
ORDER BY created_at DESC, id DESC
LIMIT $3 OFFSET $2
`

type ListAuditLogsParams struct {
	TargetID *string
	Off      int32
	Lim      int32
}

func (q *Queries) ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AdminAuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogs, arg.TargetID, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminAuditLog{}
	for rows.Next() {
		var i AdminAuditLog
		if err := rows.Scan(
			&i.ID,
			&i.AdminUserID,
			&i.AdminEmail,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.Details,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLandingPackages = `-- name: ListLandingPackages :many
SELECT id, name, storage_mb, archive_days, price_display, created_at, updated_at, show_on_landing, sort_order FROM packages WHERE show_on_landing ORDER BY sort_order, storage_mb, name
`

func (q *Queries) ListLandingPackages(ctx context.Context) ([]Package, error) {
	rows, err := q.db.Query(ctx, listLandingPackages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Package{}
	for rows.Next() {
		var i Package
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.StorageMb,
			&i.ArchiveDays,
			&i.PriceDisplay,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ShowOnLanding,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPackages = `-- name: ListPackages :many

SELECT p.id, p.name, p.storage_mb, p.archive_days, p.price_display, p.created_at, p.updated_at, p.show_on_landing, p.sort_order, (SELECT count(*) FROM wedding_packages wp WHERE wp.package_id = p.id) AS weddings -- tenant:ignore hitung pemakai paket
FROM packages p ORDER BY p.sort_order, p.storage_mb, p.name
`

type ListPackagesRow struct {
	ID            uuid.UUID
	Name          string
	StorageMb     int32
	ArchiveDays   int32
	PriceDisplay  string
	CreatedAt     time.Time
	UpdatedAt     time.Time
	ShowOnLanding bool
	SortOrder     int32
	Weddings      int64
}

// Modul admin hanya menyentuh tabel miliknya sendiri: packages,
// wedding_packages, admin_audit_logs. Data modul lain lewat service modul itu.
func (q *Queries) ListPackages(ctx context.Context) ([]ListPackagesRow, error) {
	rows, err := q.db.Query(ctx, listPackages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPackagesRow{}
	for rows.Next() {
		var i ListPackagesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.StorageMb,
			&i.ArchiveDays,
			&i.PriceDisplay,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ShowOnLanding,
			&i.SortOrder,
			&i.Weddings,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unassignPackage = `-- name: UnassignPackage :execrows
DELETE FROM wedding_packages WHERE wedding_id = $1
`

func (q *Queries) UnassignPackage(ctx context.Context, weddingID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, unassignPackage, weddingID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updatePackage = `-- name: UpdatePackage :one
UPDATE packages SET name = $2, storage_mb = $3, archive_days = $4, price_display = $5,
    show_on_landing = $6, sort_order = $7
WHERE id = $1
RETURNING id, name, storage_mb, archive_days, price_display, created_at, updated_at, show_on_landing, sort_order
`

type UpdatePackageParams struct {
	ID            uuid.UUID
	Name          string
	StorageMb     int32
	ArchiveDays   int32
	PriceDisplay  string
	ShowOnLanding bool
	SortOrder     int32
}

func (q *Queries) UpdatePackage(ctx context.Context, arg UpdatePackageParams) (Package, error) {
	row := q.db.QueryRow(ctx, updatePackage,
		arg.ID,
		arg.Name,
		arg.StorageMb,
		arg.ArchiveDays,
		arg.PriceDisplay,
		arg.ShowOnLanding,
		arg.SortOrder,
	)
	var i Package
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.StorageMb,
		&i.ArchiveDays,
		&i.PriceDisplay,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ShowOnLanding,
		&i.SortOrder,
	)
	return i, err
}
