// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: theme_settings.sql

package themedb

import (
	"context"

	"github.com/google/uuid"
)

const getSettings = `-- name: GetSettings :one
SELECT wedding_id, primary_color, font_heading, font_body, background_value, cover_image_url, created_at, updated_at FROM wedding_theme_settings WHERE wedding_id = $1
`

func (q *Queries) GetSettings(ctx context.Context, weddingID uuid.UUID) (WeddingThemeSetting, error) {
	row := q.db.QueryRow(ctx, getSettings, weddingID)
	var i WeddingThemeSetting
	err := row.Scan(
		&i.WeddingID,
		&i.PrimaryColor,
		&i.FontHeading,
		&i.FontBody,
		&i.BackgroundValue,
		&i.CoverImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSettings = `-- name: UpsertSettings :exec
INSERT INTO wedding_theme_settings (wedding_id, primary_color, font_heading, font_body, background_value, cover_image_url)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (wedding_id) DO UPDATE
SET primary_color = EXCLUDED.primary_color, font_heading = EXCLUDED.font_heading,
    font_body = EXCLUDED.font_body, background_value = EXCLUDED.background_value,
    cover_image_url = EXCLUDED.cover_image_url
`

type UpsertSettingsParams struct {
	WeddingID       uuid.UUID
	PrimaryColor    *string
	FontHeading     *string
	FontBody        *string
	BackgroundValue *string
	CoverImageUrl   *string
}

func (q *Queries) UpsertSettings(ctx context.Context, arg UpsertSettingsParams) error {
	_, err := q.db.Exec(ctx, upsertSettings,
		arg.WeddingID,
		arg.PrimaryColor,
		arg.FontHeading,
		arg.FontBody,
		arg.BackgroundValue,
		arg.CoverImageUrl,
	)
	return err
}
