// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identities.sql

package authdb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createIdentity = `-- name: CreateIdentity :exec
INSERT INTO user_identities (provider, subject, user_id, email) VALUES ($1, $2, $3, $4)
`

type CreateIdentityParams struct {
	Provider string
	Subject  string
	UserID   uuid.UUID
	Email    string
}

func (q *Queries) CreateIdentity(ctx context.Context, arg CreateIdentityParams) error {
	_, err := q.db.Exec(ctx, createIdentity,
		arg.Provider,
		arg.Subject,
		arg.UserID,
		arg.Email,
	)
	return err
}

const getUserByIdentity = `-- name: GetUserByIdentity :one
SELECT u.id, u.email, u.password_hash, u.name, u.role, u.email_verified_at, u.created_at, u.updated_at, u.disabled_at FROM user_identities i JOIN users u ON u.id = i.user_id
WHERE i.provider = $1 AND i.subject = $2
`

type GetUserByIdentityParams struct {
	Provider string
	Subject  string
}

func (q *Queries) GetUserByIdentity(ctx context.Context, arg GetUserByIdentityParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByIdentity, arg.Provider, arg.Subject)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Role,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DisabledAt,
	)
	return i, err
}

const markEmailVerified = `-- name: MarkEmailVerified :exec
UPDATE users SET email_verified_at = COALESCE(email_verified_at, $2) WHERE id = $1
`

type MarkEmailVerifiedParams struct {
	ID              uuid.UUID
	EmailVerifiedAt *time.Time
}

func (q *Queries) MarkEmailVerified(ctx context.Context, arg MarkEmailVerifiedParams) error {
	_, err := q.db.Exec(ctx, markEmailVerified, arg.ID, arg.EmailVerifiedAt)
	return err
}
