// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package layouts

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

// uiIcons: ikon garis (viewBox 24, stroke 1.8, ujung membulat) untuk kerangka
// dashboard — digambar sendiri, tanpa library ikon (aturan wajib #7).
var uiIcons = map[string]string{
	"menu":     "M4 7h16M4 12h16M4 17h16",
	"close":    "M6 6l12 12M18 6L6 18",
	"home":     "M3.5 11.2L12 4l8.5 7.2M5.5 9.8V20h13V9.8M10 20v-5.5h4V20",
	"heart":    "M12 20.2s-7.4-4.5-9.1-9.4C1.8 7.6 3.9 4.6 7 4.6c1.9 0 3.5 1 5 2.9 1.5-1.9 3.1-2.9 5-2.9 3.1 0 5.2 3 4.1 6.2-1.7 4.9-9.1 9.4-9.1 9.4z",
	"plus":     "M12 5v14M5 12h14",
	"shield":   "M12 3.2l7.5 2.8v5.6c0 4.4-3 7.9-7.5 9.2-4.5-1.3-7.5-4.8-7.5-9.2V6L12 3.2zM9 12l2.2 2.2L15.2 10",
	"external": "M14 4.5h5.5V10M19.5 4.5l-8 8M10.5 6H6.5a1.5 1.5 0 00-1.5 1.5v10A1.5 1.5 0 006.5 19h10a1.5 1.5 0 001.5-1.5v-4",
	"logout":   "M9.5 4.5h-3A1.5 1.5 0 005 6v12a1.5 1.5 0 001.5 1.5h3M14.5 16l4-4-4-4M18.5 12H9.5",
	"chevron":  "M7 10l5 5 5-5",
}

// Icon: ikon garis dekoratif (aria-hidden); warna mengikuti teks.
func Icon(name, class string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		var templ_7745c5c3_Var2 = []any{class}
		templ_7745c5c3_Err = templ.RenderCSSItems(ctx, templ_7745c5c3_Buffer, templ_7745c5c3_Var2...)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<svg aria-hidden=\"true\" focusable=\"false\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.8\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.ResolveAttributeValue(templ.CSSClasses(templ_7745c5c3_Var2).String())
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `src/templates/layouts/icons.templ`, Line: 1, Col: 0}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var3)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\"><path d=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var4 string
		templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.ResolveAttributeValue(uiIcons[name])
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `src/templates/layouts/icons.templ`, Line: 20, Col: 25}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var4)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "\"></path></svg>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// userInitial: huruf pertama nama pengguna untuk avatar.
func userInitial(name string) string {
	for _, r := range name {
		return string(r)
	}
	return "?"
}

var _ = templruntime.GeneratedTemplate
